# Generated by Django 6.0.1 on 2026-04-30 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=63)),
                ('email_address', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Book Contributor', 'Book Contributor'), ('Commission Maker', 'Commission Maker')], default='Member', max_length=31)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
