# Generated by Django 6.0.4 on 2026-05-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': [models.Case(models.When(status='Pending', then=models.Value(0)), models.When(status='Accepted', then=models.Value(1)), models.When(status='Rejected', then=models.Value(2)), default=models.Value(3), output_field=models.IntegerField()), '-applied_on']},
        ),
    ]
