# Generated by Django 6.0.4 on 2026-05-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_missing_profiles'),
        ('localevents', '0002_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_capacity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='', upload_to='event_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Available', max_length=255),
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizers', to='localevents.event')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_event_links', to='accounts.profile')),
            ],
            options={
                'unique_together': {('event', 'organizer')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, related_name='organizer', through='localevents.EventOrganizer', through_fields=('event', 'organizer'), to='accounts.profile'),
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_registrant', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signup', to='localevents.event')),
                ('user_registrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_signup', to='accounts.profile')),
            ],
        ),
    ]
